spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:9090
          predicates:
            - Path=${service.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:9091
          predicates:
            - Path=${service.api-prefix}/profile/**
          filters:
            - StripPrefix=2
server:
  port: 9000
service:
  api-prefix: /api/v1